dist: xenial
os: linux
language: python

python:
  - 3.6.12
  - 3.7.9
  - 3.8.7
  - 3.9.1
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - python: 3.8.7
    - python: nightly

install:
  - pip install codecov
  - pip install .       # Test installation correctness
  - pip install .[dev]  # Test development dependencies

script:
  - pytest -v --cov-report=xml --cov=galactica # Test against installed code + coverage report

after_success:
  - codecov
