dist: xenial
language: python
sudo: false

python:
  - 3.6.11
  - 3.7.8
  - 3.8.3
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install codecov
  - pip install .       # Test installation correctness
  - pip install .[dev]  # Test development dependencies

script:
  - pytest -v --cov-report=xml --cov=galactica # Test against installed code + coverage report

after_success:
  - codecov
