dist: xenial
language: python
sudo: false

# addons for Scipy with Python 3.8-dev
addons:
  apt:
    packages: &common_packages
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - libsuitesparse-dev
    - ccache
    - swig
    - libmpc-dev

python:
  - 3.6
  - 3.7
  - 3.8
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install codecov
  - pip install .       # Test installation correctness
  - pip install .[dev]  # Test development dependencies

script:
  - pytest -v --cov-report=xml --cov=galactica # Test against installed code + coverage report

after_success:
  - codecov
