[project]
name = "galactica"
version = "0.1.0"
description = "Galactic multiphase chemical evolution model"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "pyyaml>=6.0",
  "numpy>=2.2",
  "scipy>=1.15",
  "starmatrix>=1.7.4",
]
