name: tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        python-version:
          - 3.7.17
          - 3.8.18
          - 3.9.19
          - 3.10.14
          - 3.11.9
          - 3.12.3
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pytest
        pip install codecov
    - name: Install Galactica
      run: |
        pip install .
        pip install .[dev]
    - name: Test against installed code
      run: pytest -v --cov-report=xml --cov=galactica
    - uses: codecov/codecov-action@v3
